/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Inova Sind API
 * API para o projeto Inova Sind
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from '../../fetch';
export type Get200 = {
  message: string;
};

export type CreateAssessmentBody = {
  /** @minLength 1 */
  assessmentComments: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  assessmentScore: number;
};

export type CreateAssessment201 = {
  organizationId: string;
  userId: string;
  /** @nullable */
  assessmentComments: string | null;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  assessmentScore: number;
};

export type CreateAssessment401 = {
  error: string;
  code: string;
};

export type CreateAssessment500 = {
  error: string;
  code: string;
};

export type CreateOrganizationBody = {
  /** @minLength 1 */
  name: string;
  cnpj?: string;
  address?: string;
  /** @minLength 11 */
  phone: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email?: string;
  contact?: string;
};

export type CreateOrganization201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @nullable */
  cnpj?: string | null;
  /** @nullable */
  address?: string | null;
  phone: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  contact?: string | null;
};

export type CreateOrganization400 = {
  error: string;
  code: string;
};

export type CreateOrganization401 = {
  error: string;
  code: string;
};

export type CreateOrganization500 = {
  error: string;
  code: string;
};

export type GetOrganizations200Item = {
  id: string;
  name: string;
};

export type GetOrganizations401 = {
  error: string;
  code: string;
};

export type GetOrganizations500 = {
  error: string;
  code: string;
};

export type CreateOrganizationServiceBody = {
  organizationId: string;
  serviceId: string;
  user: string;
};

export type CreateOrganizationService201 = {
  id: string;
};

export type CreateOrganizationService401 = {
  error: string;
  code: string;
};

export type CreateOrganizationService500 = {
  error: string;
  code: string;
};

export type CreateOrganizationProductBody = {
  organizationId: string;
  productId: string;
  user: string;
};

export type CreateOrganizationProduct201 = {
  id: string;
};

export type CreateOrganizationProduct401 = {
  error: string;
  code: string;
};

export type CreateOrganizationProduct500 = {
  error: string;
  code: string;
};

export type CreateProductBody = {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
};

export type CreateProduct200 = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
};

export type CreateProduct401 = {
  error: string;
  code: string;
};

export type CreateProduct500 = {
  error: string;
  code: string;
};

export type GetProducts200Item = {
  id: string;
  name: string;
};

export type GetProducts401 = {
  error: string;
  code: string;
};

export type GetProducts500 = {
  error: string;
  code: string;
};

export type CreateServiceBody = {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
};

export type CreateService201 = {
  id: string;
  name: string;
  description: string;
};

export type CreateService401 = {
  error: string;
  code: string;
};

export type CreateService500 = {
  error: string;
  code: string;
};

export type GetServices200Item = {
  id: string;
  name: string;
};

export type GetServices401 = {
  error: string;
  code: string;
};

export type GetServices500 = {
  error: string;
  code: string;
};

export type getResponse200 = {
  data: Get200
  status: 200
}

export type getResponseSuccess = (getResponse200) & {
  headers: Headers;
};
;

export type getResponse = (getResponseSuccess)

export const getGetUrl = () => {




  return `/`
}

/**
 * Hello World
 */
export const get = async ( options?: RequestInit): Promise<getResponse> => {

  return customFetch<getResponse>(getGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type createAssessmentResponse201 = {
  data: CreateAssessment201
  status: 201
}

export type createAssessmentResponse401 = {
  data: CreateAssessment401
  status: 401
}

export type createAssessmentResponse500 = {
  data: CreateAssessment500
  status: 500
}

export type createAssessmentResponseSuccess = (createAssessmentResponse201) & {
  headers: Headers;
};
export type createAssessmentResponseError = (createAssessmentResponse401 | createAssessmentResponse500) & {
  headers: Headers;
};

export type createAssessmentResponse = (createAssessmentResponseSuccess | createAssessmentResponseError)

export const getCreateAssessmentUrl = (id: string,) => {




  return `/assessment/organization/${id}`
}

/**
 * @summary Create a assessment
 */
export const createAssessment = async (id: string,
    createAssessmentBody: CreateAssessmentBody, options?: RequestInit): Promise<createAssessmentResponse> => {

  return customFetch<createAssessmentResponse>(getCreateAssessmentUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAssessmentBody)
  }
);}



export type createOrganizationResponse201 = {
  data: CreateOrganization201
  status: 201
}

export type createOrganizationResponse400 = {
  data: CreateOrganization400
  status: 400
}

export type createOrganizationResponse401 = {
  data: CreateOrganization401
  status: 401
}

export type createOrganizationResponse500 = {
  data: CreateOrganization500
  status: 500
}

export type createOrganizationResponseSuccess = (createOrganizationResponse201) & {
  headers: Headers;
};
export type createOrganizationResponseError = (createOrganizationResponse400 | createOrganizationResponse401 | createOrganizationResponse500) & {
  headers: Headers;
};

export type createOrganizationResponse = (createOrganizationResponseSuccess | createOrganizationResponseError)

export const getCreateOrganizationUrl = () => {




  return `/organization/`
}

/**
 * @summary Create a organization
 */
export const createOrganization = async (createOrganizationBody: CreateOrganizationBody, options?: RequestInit): Promise<createOrganizationResponse> => {

  return customFetch<createOrganizationResponse>(getCreateOrganizationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationBody)
  }
);}



export type getOrganizationsResponse200 = {
  data: GetOrganizations200Item[]
  status: 200
}

export type getOrganizationsResponse401 = {
  data: GetOrganizations401
  status: 401
}

export type getOrganizationsResponse500 = {
  data: GetOrganizations500
  status: 500
}

export type getOrganizationsResponseSuccess = (getOrganizationsResponse200) & {
  headers: Headers;
};
export type getOrganizationsResponseError = (getOrganizationsResponse401 | getOrganizationsResponse500) & {
  headers: Headers;
};

export type getOrganizationsResponse = (getOrganizationsResponseSuccess | getOrganizationsResponseError)

export const getGetOrganizationsUrl = () => {




  return `/organization/`
}

/**
 * @summary Get organizations
 */
export const getOrganizations = async ( options?: RequestInit): Promise<getOrganizationsResponse> => {

  return customFetch<getOrganizationsResponse>(getGetOrganizationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type createOrganizationServiceResponse201 = {
  data: CreateOrganizationService201
  status: 201
}

export type createOrganizationServiceResponse401 = {
  data: CreateOrganizationService401
  status: 401
}

export type createOrganizationServiceResponse500 = {
  data: CreateOrganizationService500
  status: 500
}

export type createOrganizationServiceResponseSuccess = (createOrganizationServiceResponse201) & {
  headers: Headers;
};
export type createOrganizationServiceResponseError = (createOrganizationServiceResponse401 | createOrganizationServiceResponse500) & {
  headers: Headers;
};

export type createOrganizationServiceResponse = (createOrganizationServiceResponseSuccess | createOrganizationServiceResponseError)

export const getCreateOrganizationServiceUrl = () => {




  return `/organization/service`
}

/**
 * @summary Create a service of the organization
 */
export const createOrganizationService = async (createOrganizationServiceBody: CreateOrganizationServiceBody, options?: RequestInit): Promise<createOrganizationServiceResponse> => {

  return customFetch<createOrganizationServiceResponse>(getCreateOrganizationServiceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationServiceBody)
  }
);}



export type createOrganizationProductResponse201 = {
  data: CreateOrganizationProduct201
  status: 201
}

export type createOrganizationProductResponse401 = {
  data: CreateOrganizationProduct401
  status: 401
}

export type createOrganizationProductResponse500 = {
  data: CreateOrganizationProduct500
  status: 500
}

export type createOrganizationProductResponseSuccess = (createOrganizationProductResponse201) & {
  headers: Headers;
};
export type createOrganizationProductResponseError = (createOrganizationProductResponse401 | createOrganizationProductResponse500) & {
  headers: Headers;
};

export type createOrganizationProductResponse = (createOrganizationProductResponseSuccess | createOrganizationProductResponseError)

export const getCreateOrganizationProductUrl = () => {




  return `/organization/product`
}

/**
 * @summary Create a product of the organization
 */
export const createOrganizationProduct = async (createOrganizationProductBody: CreateOrganizationProductBody, options?: RequestInit): Promise<createOrganizationProductResponse> => {

  return customFetch<createOrganizationProductResponse>(getCreateOrganizationProductUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationProductBody)
  }
);}



export type createProductResponse200 = {
  data: CreateProduct200
  status: 200
}

export type createProductResponse401 = {
  data: CreateProduct401
  status: 401
}

export type createProductResponse500 = {
  data: CreateProduct500
  status: 500
}

export type createProductResponseSuccess = (createProductResponse200) & {
  headers: Headers;
};
export type createProductResponseError = (createProductResponse401 | createProductResponse500) & {
  headers: Headers;
};

export type createProductResponse = (createProductResponseSuccess | createProductResponseError)

export const getCreateProductUrl = (date: string,) => {




  return `/product/${date}`
}

/**
 * @summary Create a product
 */
export const createProduct = async (date: string,
    createProductBody: CreateProductBody, options?: RequestInit): Promise<createProductResponse> => {

  return customFetch<createProductResponse>(getCreateProductUrl(date),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProductBody)
  }
);}



export type getProductsResponse200 = {
  data: GetProducts200Item[]
  status: 200
}

export type getProductsResponse401 = {
  data: GetProducts401
  status: 401
}

export type getProductsResponse500 = {
  data: GetProducts500
  status: 500
}

export type getProductsResponseSuccess = (getProductsResponse200) & {
  headers: Headers;
};
export type getProductsResponseError = (getProductsResponse401 | getProductsResponse500) & {
  headers: Headers;
};

export type getProductsResponse = (getProductsResponseSuccess | getProductsResponseError)

export const getGetProductsUrl = () => {




  return `/product/`
}

/**
 * @summary Get products
 */
export const getProducts = async ( options?: RequestInit): Promise<getProductsResponse> => {

  return customFetch<getProductsResponse>(getGetProductsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type createServiceResponse201 = {
  data: CreateService201
  status: 201
}

export type createServiceResponse401 = {
  data: CreateService401
  status: 401
}

export type createServiceResponse500 = {
  data: CreateService500
  status: 500
}

export type createServiceResponseSuccess = (createServiceResponse201) & {
  headers: Headers;
};
export type createServiceResponseError = (createServiceResponse401 | createServiceResponse500) & {
  headers: Headers;
};

export type createServiceResponse = (createServiceResponseSuccess | createServiceResponseError)

export const getCreateServiceUrl = () => {




  return `/service/`
}

/**
 * @summary Create a service
 */
export const createService = async (createServiceBody: CreateServiceBody, options?: RequestInit): Promise<createServiceResponse> => {

  return customFetch<createServiceResponse>(getCreateServiceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createServiceBody)
  }
);}



export type getServicesResponse200 = {
  data: GetServices200Item[]
  status: 200
}

export type getServicesResponse401 = {
  data: GetServices401
  status: 401
}

export type getServicesResponse500 = {
  data: GetServices500
  status: 500
}

export type getServicesResponseSuccess = (getServicesResponse200) & {
  headers: Headers;
};
export type getServicesResponseError = (getServicesResponse401 | getServicesResponse500) & {
  headers: Headers;
};

export type getServicesResponse = (getServicesResponseSuccess | getServicesResponseError)

export const getGetServicesUrl = (date: string,) => {




  return `/service/${date}`
}

/**
 * @summary Get services
 */
export const getServices = async (date: string, options?: RequestInit): Promise<getServicesResponse> => {

  return customFetch<getServicesResponse>(getGetServicesUrl(date),
  {
    ...options,
    method: 'GET'


  }
);}
