/**
 * Generated by orval v8.16.0 🍺
 * Do not edit manually.
 * Inova Sind API
 * API para o projeto Inova Sind
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from '../../fetch';
export type Get200 = {
  message: string;
};

export type CreateAssessmentBody = {
  /** @minLength 1 */
  assessmentComments: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  assessmentScore: number;
};

export type CreateAssessment201 = {
  organizationId: string;
  userId: string;
  /** @nullable */
  assessmentComments: string | null;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  assessmentScore: number;
};

export type CreateAssessment401 = {
  error: string;
  code: string;
};

export type CreateAssessment500 = {
  error: string;
  code: string;
};

export type CreateOrganizationBody = {
  /** @minLength 1 */
  name: string;
  cnpj?: string;
  address?: string;
  /** @minLength 11 */
  phone: string;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email?: string;
  contact?: string;
};

export type CreateOrganization201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @nullable */
  cnpj?: string | null;
  /** @nullable */
  address?: string | null;
  phone: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  contact?: string | null;
};

export type CreateOrganization400 = {
  error: string;
  code: string;
};

export type CreateOrganization401 = {
  error: string;
  code: string;
};

export type CreateOrganization500 = {
  error: string;
  code: string;
};

export type GetOrganizations200Item = {
  id: string;
  name: string;
  /** @nullable */
  averageScore: number | null;
};

export type GetOrganizations401 = {
  error: string;
  code: string;
};

export type GetOrganizations500 = {
  error: string;
  code: string;
};

export type CreateOrganizationServiceBody = {
  organizationId: string;
  serviceId: string;
  user: string;
};

export type CreateOrganizationService201 = {
  id: string;
};

export type CreateOrganizationService401 = {
  error: string;
  code: string;
};

export type CreateOrganizationService500 = {
  error: string;
  code: string;
};

export type CreateOrganizationProductBody = {
  organizationId: string;
  productId: string;
  user: string;
};

export type CreateOrganizationProduct201 = {
  id: string;
};

export type CreateOrganizationProduct401 = {
  error: string;
  code: string;
};

export type CreateOrganizationProduct500 = {
  error: string;
  code: string;
};

export type GetOrganization200ProductsItem = {
  name: string;
  /** @nullable */
  description: string | null;
};

export type GetOrganization200ServicesItem = {
  name: string;
  description: string;
};

export type GetOrganization200AssessmentsItemUser = {
  name: string;
};

export type GetOrganization200AssessmentsItem = {
  user: GetOrganization200AssessmentsItemUser;
  assessmentDate: string;
  /** @nullable */
  assessmentComments: string | null;
  assessmentScore: number;
};

export type GetOrganization200 = {
  id: string;
  name: string;
  /** @nullable */
  cnpj: string | null;
  /** @nullable */
  address: string | null;
  phone: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  contact: string | null;
  products: GetOrganization200ProductsItem[];
  services: GetOrganization200ServicesItem[];
  assessments: GetOrganization200AssessmentsItem[];
};

export type GetOrganization401 = {
  error: string;
  code: string;
};

export type GetOrganization404 = {
  error: string;
  code: string;
};

export type GetOrganization500 = {
  error: string;
  code: string;
};

export type GetOrganizationsSearchParams = {
/**
 * @minLength 1
 */
search: string;
};

export type GetOrganizationsSearch200ItemProductsItem = {
  name: string;
  /** @nullable */
  description: string | null;
};

export type GetOrganizationsSearch200ItemServicesItem = {
  name: string;
  description: string;
};

export type GetOrganizationsSearch200ItemAssessmentsItemUser = {
  name: string;
};

export type GetOrganizationsSearch200ItemAssessmentsItem = {
  user: GetOrganizationsSearch200ItemAssessmentsItemUser;
  assessmentDate: string;
  /** @nullable */
  assessmentComments: string | null;
  assessmentScore: number;
};

export type GetOrganizationsSearch200Item = {
  id: string;
  name: string;
  /** @nullable */
  cnpj: string | null;
  /** @nullable */
  address: string | null;
  phone: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  contact: string | null;
  products: GetOrganizationsSearch200ItemProductsItem[];
  services: GetOrganizationsSearch200ItemServicesItem[];
  assessments: GetOrganizationsSearch200ItemAssessmentsItem[];
};

export type GetOrganizationsSearch401 = {
  error: string;
  code: string;
};

export type GetOrganizationsSearch500 = {
  error: string;
  code: string;
};

export type CreateProductBody = {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  /** @minLength 1 */
  typeId: string;
};

export type CreateProduct200 = {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  typeId: string;
};

export type CreateProduct401 = {
  error: string;
  code: string;
};

export type CreateProduct500 = {
  error: string;
  code: string;
};

export type GetProducts200Item = {
  id: string;
  name: string;
  typeId: string;
};

export type GetProducts401 = {
  error: string;
  code: string;
};

export type GetProducts500 = {
  error: string;
  code: string;
};

export type CreateServiceBody = {
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  description: string;
  /** @minLength 1 */
  typeId: string;
};

export type CreateService201 = {
  id: string;
  name: string;
  description: string;
  typeId: string;
};

export type CreateService401 = {
  error: string;
  code: string;
};

export type CreateService500 = {
  error: string;
  code: string;
};

export type GetServices200Item = {
  id: string;
  name: string;
  typeId: string;
};

export type GetServices401 = {
  error: string;
  code: string;
};

export type GetServices500 = {
  error: string;
  code: string;
};

export type GetTypeProductService200ItemType = typeof GetTypeProductService200ItemType[keyof typeof GetTypeProductService200ItemType];


export const GetTypeProductService200ItemType = {
  PRODUCT: 'PRODUCT',
  SERVICE: 'SERVICE',
} as const;

export type GetTypeProductService200Item = {
  id: string;
  name: string;
  type: GetTypeProductService200ItemType;
};

export type GetTypeProductService401 = {
  error: string;
  code: string;
};

export type GetTypeProductService500 = {
  error: string;
  code: string;
};

export type CreateTypeProductServiceBodyType = typeof CreateTypeProductServiceBodyType[keyof typeof CreateTypeProductServiceBodyType];


export const CreateTypeProductServiceBodyType = {
  PRODUCT: 'PRODUCT',
  SERVICE: 'SERVICE',
} as const;

export type CreateTypeProductServiceBody = {
  /** @minLength 1 */
  name: string;
  type: CreateTypeProductServiceBodyType;
};

export type CreateTypeProductService201Type = typeof CreateTypeProductService201Type[keyof typeof CreateTypeProductService201Type];


export const CreateTypeProductService201Type = {
  PRODUCT: 'PRODUCT',
  SERVICE: 'SERVICE',
} as const;

export type CreateTypeProductService201 = {
  id: string;
  name: string;
  type: CreateTypeProductService201Type;
};

export type CreateTypeProductService401 = {
  error: string;
  code: string;
};

export type CreateTypeProductService500 = {
  error: string;
  code: string;
};

export type getResponse200 = {
  data: Get200
  status: 200
}

export type getResponseSuccess = (getResponse200) & {
  headers: Headers;
};
;

export type getResponse = (getResponseSuccess)

export const getGetUrl = () => {




  return `/`
}

/**
 * Hello World
 */
export const get = async ( options?: RequestInit): Promise<getResponse> => {

  return customFetch<getResponse>(getGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type createAssessmentResponse201 = {
  data: CreateAssessment201
  status: 201
}

export type createAssessmentResponse401 = {
  data: CreateAssessment401
  status: 401
}

export type createAssessmentResponse500 = {
  data: CreateAssessment500
  status: 500
}

export type createAssessmentResponseSuccess = (createAssessmentResponse201) & {
  headers: Headers;
};
export type createAssessmentResponseError = (createAssessmentResponse401 | createAssessmentResponse500) & {
  headers: Headers;
};

export type createAssessmentResponse = (createAssessmentResponseSuccess | createAssessmentResponseError)

export const getCreateAssessmentUrl = (id: string,) => {




  return `/assessment/organization/${id}`
}

/**
 * @summary Create a assessment
 */
export const createAssessment = async (id: string,
    createAssessmentBody: CreateAssessmentBody, options?: RequestInit): Promise<createAssessmentResponse> => {

  return customFetch<createAssessmentResponse>(getCreateAssessmentUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAssessmentBody)
  }
);}



export type createOrganizationResponse201 = {
  data: CreateOrganization201
  status: 201
}

export type createOrganizationResponse400 = {
  data: CreateOrganization400
  status: 400
}

export type createOrganizationResponse401 = {
  data: CreateOrganization401
  status: 401
}

export type createOrganizationResponse500 = {
  data: CreateOrganization500
  status: 500
}

export type createOrganizationResponseSuccess = (createOrganizationResponse201) & {
  headers: Headers;
};
export type createOrganizationResponseError = (createOrganizationResponse400 | createOrganizationResponse401 | createOrganizationResponse500) & {
  headers: Headers;
};

export type createOrganizationResponse = (createOrganizationResponseSuccess | createOrganizationResponseError)

export const getCreateOrganizationUrl = () => {




  return `/organization/`
}

/**
 * @summary Create a organization
 */
export const createOrganization = async (createOrganizationBody: CreateOrganizationBody, options?: RequestInit): Promise<createOrganizationResponse> => {

  return customFetch<createOrganizationResponse>(getCreateOrganizationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationBody)
  }
);}



export type getOrganizationsResponse200 = {
  data: GetOrganizations200Item[]
  status: 200
}

export type getOrganizationsResponse401 = {
  data: GetOrganizations401
  status: 401
}

export type getOrganizationsResponse500 = {
  data: GetOrganizations500
  status: 500
}

export type getOrganizationsResponseSuccess = (getOrganizationsResponse200) & {
  headers: Headers;
};
export type getOrganizationsResponseError = (getOrganizationsResponse401 | getOrganizationsResponse500) & {
  headers: Headers;
};

export type getOrganizationsResponse = (getOrganizationsResponseSuccess | getOrganizationsResponseError)

export const getGetOrganizationsUrl = () => {




  return `/organization/`
}

/**
 * @summary Get organizations
 */
export const getOrganizations = async ( options?: RequestInit): Promise<getOrganizationsResponse> => {

  return customFetch<getOrganizationsResponse>(getGetOrganizationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type createOrganizationServiceResponse201 = {
  data: CreateOrganizationService201
  status: 201
}

export type createOrganizationServiceResponse401 = {
  data: CreateOrganizationService401
  status: 401
}

export type createOrganizationServiceResponse500 = {
  data: CreateOrganizationService500
  status: 500
}

export type createOrganizationServiceResponseSuccess = (createOrganizationServiceResponse201) & {
  headers: Headers;
};
export type createOrganizationServiceResponseError = (createOrganizationServiceResponse401 | createOrganizationServiceResponse500) & {
  headers: Headers;
};

export type createOrganizationServiceResponse = (createOrganizationServiceResponseSuccess | createOrganizationServiceResponseError)

export const getCreateOrganizationServiceUrl = () => {




  return `/organization/service`
}

/**
 * @summary Create a service of the organization
 */
export const createOrganizationService = async (createOrganizationServiceBody: CreateOrganizationServiceBody, options?: RequestInit): Promise<createOrganizationServiceResponse> => {

  return customFetch<createOrganizationServiceResponse>(getCreateOrganizationServiceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationServiceBody)
  }
);}



export type createOrganizationProductResponse201 = {
  data: CreateOrganizationProduct201
  status: 201
}

export type createOrganizationProductResponse401 = {
  data: CreateOrganizationProduct401
  status: 401
}

export type createOrganizationProductResponse500 = {
  data: CreateOrganizationProduct500
  status: 500
}

export type createOrganizationProductResponseSuccess = (createOrganizationProductResponse201) & {
  headers: Headers;
};
export type createOrganizationProductResponseError = (createOrganizationProductResponse401 | createOrganizationProductResponse500) & {
  headers: Headers;
};

export type createOrganizationProductResponse = (createOrganizationProductResponseSuccess | createOrganizationProductResponseError)

export const getCreateOrganizationProductUrl = () => {




  return `/organization/product`
}

/**
 * @summary Create a product of the organization
 */
export const createOrganizationProduct = async (createOrganizationProductBody: CreateOrganizationProductBody, options?: RequestInit): Promise<createOrganizationProductResponse> => {

  return customFetch<createOrganizationProductResponse>(getCreateOrganizationProductUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createOrganizationProductBody)
  }
);}



export type getOrganizationResponse200 = {
  data: GetOrganization200
  status: 200
}

export type getOrganizationResponse401 = {
  data: GetOrganization401
  status: 401
}

export type getOrganizationResponse404 = {
  data: GetOrganization404
  status: 404
}

export type getOrganizationResponse500 = {
  data: GetOrganization500
  status: 500
}

export type getOrganizationResponseSuccess = (getOrganizationResponse200) & {
  headers: Headers;
};
export type getOrganizationResponseError = (getOrganizationResponse401 | getOrganizationResponse404 | getOrganizationResponse500) & {
  headers: Headers;
};

export type getOrganizationResponse = (getOrganizationResponseSuccess | getOrganizationResponseError)

export const getGetOrganizationUrl = (id: string,) => {




  return `/organization/${id}`
}

/**
 * @summary Get an organization by id
 */
export const getOrganization = async (id: string, options?: RequestInit): Promise<getOrganizationResponse> => {

  return customFetch<getOrganizationResponse>(getGetOrganizationUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}



export type getOrganizationsSearchResponse200 = {
  data: GetOrganizationsSearch200Item[]
  status: 200
}

export type getOrganizationsSearchResponse401 = {
  data: GetOrganizationsSearch401
  status: 401
}

export type getOrganizationsSearchResponse500 = {
  data: GetOrganizationsSearch500
  status: 500
}

export type getOrganizationsSearchResponseSuccess = (getOrganizationsSearchResponse200) & {
  headers: Headers;
};
export type getOrganizationsSearchResponseError = (getOrganizationsSearchResponse401 | getOrganizationsSearchResponse500) & {
  headers: Headers;
};

export type getOrganizationsSearchResponse = (getOrganizationsSearchResponseSuccess | getOrganizationsSearchResponseError)

export const getGetOrganizationsSearchUrl = (params: GetOrganizationsSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/organization/search?${stringifiedParams}` : `/organization/search`
}

/**
 * @summary Search organizations by name, service or product
 */
export const getOrganizationsSearch = async (params: GetOrganizationsSearchParams, options?: RequestInit): Promise<getOrganizationsSearchResponse> => {

  return customFetch<getOrganizationsSearchResponse>(getGetOrganizationsSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type createProductResponse200 = {
  data: CreateProduct200
  status: 200
}

export type createProductResponse401 = {
  data: CreateProduct401
  status: 401
}

export type createProductResponse500 = {
  data: CreateProduct500
  status: 500
}

export type createProductResponseSuccess = (createProductResponse200) & {
  headers: Headers;
};
export type createProductResponseError = (createProductResponse401 | createProductResponse500) & {
  headers: Headers;
};

export type createProductResponse = (createProductResponseSuccess | createProductResponseError)

export const getCreateProductUrl = (date: string,) => {




  return `/product/${date}`
}

/**
 * @summary Create a product
 */
export const createProduct = async (date: string,
    createProductBody: CreateProductBody, options?: RequestInit): Promise<createProductResponse> => {

  return customFetch<createProductResponse>(getCreateProductUrl(date),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProductBody)
  }
);}



export type getProductsResponse200 = {
  data: GetProducts200Item[]
  status: 200
}

export type getProductsResponse401 = {
  data: GetProducts401
  status: 401
}

export type getProductsResponse500 = {
  data: GetProducts500
  status: 500
}

export type getProductsResponseSuccess = (getProductsResponse200) & {
  headers: Headers;
};
export type getProductsResponseError = (getProductsResponse401 | getProductsResponse500) & {
  headers: Headers;
};

export type getProductsResponse = (getProductsResponseSuccess | getProductsResponseError)

export const getGetProductsUrl = () => {




  return `/product/`
}

/**
 * @summary Get products
 */
export const getProducts = async ( options?: RequestInit): Promise<getProductsResponse> => {

  return customFetch<getProductsResponse>(getGetProductsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type createServiceResponse201 = {
  data: CreateService201
  status: 201
}

export type createServiceResponse401 = {
  data: CreateService401
  status: 401
}

export type createServiceResponse500 = {
  data: CreateService500
  status: 500
}

export type createServiceResponseSuccess = (createServiceResponse201) & {
  headers: Headers;
};
export type createServiceResponseError = (createServiceResponse401 | createServiceResponse500) & {
  headers: Headers;
};

export type createServiceResponse = (createServiceResponseSuccess | createServiceResponseError)

export const getCreateServiceUrl = () => {




  return `/service/`
}

/**
 * @summary Create a service
 */
export const createService = async (createServiceBody: CreateServiceBody, options?: RequestInit): Promise<createServiceResponse> => {

  return customFetch<createServiceResponse>(getCreateServiceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createServiceBody)
  }
);}



export type getServicesResponse200 = {
  data: GetServices200Item[]
  status: 200
}

export type getServicesResponse401 = {
  data: GetServices401
  status: 401
}

export type getServicesResponse500 = {
  data: GetServices500
  status: 500
}

export type getServicesResponseSuccess = (getServicesResponse200) & {
  headers: Headers;
};
export type getServicesResponseError = (getServicesResponse401 | getServicesResponse500) & {
  headers: Headers;
};

export type getServicesResponse = (getServicesResponseSuccess | getServicesResponseError)

export const getGetServicesUrl = (date: string,) => {




  return `/service/${date}`
}

/**
 * @summary Get services
 */
export const getServices = async (date: string, options?: RequestInit): Promise<getServicesResponse> => {

  return customFetch<getServicesResponse>(getGetServicesUrl(date),
  {
    ...options,
    method: 'GET'


  }
);}



export type getTypeProductServiceResponse200 = {
  data: GetTypeProductService200Item[]
  status: 200
}

export type getTypeProductServiceResponse401 = {
  data: GetTypeProductService401
  status: 401
}

export type getTypeProductServiceResponse500 = {
  data: GetTypeProductService500
  status: 500
}

export type getTypeProductServiceResponseSuccess = (getTypeProductServiceResponse200) & {
  headers: Headers;
};
export type getTypeProductServiceResponseError = (getTypeProductServiceResponse401 | getTypeProductServiceResponse500) & {
  headers: Headers;
};

export type getTypeProductServiceResponse = (getTypeProductServiceResponseSuccess | getTypeProductServiceResponseError)

export const getGetTypeProductServiceUrl = () => {




  return `/types/`
}

/**
 * @summary Get types of products and services
 */
export const getTypeProductService = async ( options?: RequestInit): Promise<getTypeProductServiceResponse> => {

  return customFetch<getTypeProductServiceResponse>(getGetTypeProductServiceUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type createTypeProductServiceResponse201 = {
  data: CreateTypeProductService201
  status: 201
}

export type createTypeProductServiceResponse401 = {
  data: CreateTypeProductService401
  status: 401
}

export type createTypeProductServiceResponse500 = {
  data: CreateTypeProductService500
  status: 500
}

export type createTypeProductServiceResponseSuccess = (createTypeProductServiceResponse201) & {
  headers: Headers;
};
export type createTypeProductServiceResponseError = (createTypeProductServiceResponse401 | createTypeProductServiceResponse500) & {
  headers: Headers;
};

export type createTypeProductServiceResponse = (createTypeProductServiceResponseSuccess | createTypeProductServiceResponseError)

export const getCreateTypeProductServiceUrl = () => {




  return `/types/`
}

/**
 * @summary Create a type of product or service
 */
export const createTypeProductService = async (createTypeProductServiceBody: CreateTypeProductServiceBody, options?: RequestInit): Promise<createTypeProductServiceResponse> => {

  return customFetch<createTypeProductServiceResponse>(getCreateTypeProductServiceUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTypeProductServiceBody)
  }
);}
